apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: hello-8010
  namespace: flux-system
spec:
  interval: 1m
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./clusters/carakube-demo/apps/hello-8010
  targetNamespace: default
  wait: true
  timeout: 2m
  healthChecks:
    - kind: Deployment
      name: hello-8010
      namespace: default
